/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import model.CityDirectory;
import model.CommunityDirectory;
import model.HouseDirectory;

/**
 *
 * @author shrey
 */

public class communityAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdmin
     */
    HouseDirectory houseDirectory;
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    
    public communityAdminJPanel(CityDirectory cityDirectory, CommunityDirectory communityDirectory, HouseDirectory houseDirectory) throws Exception {
        initComponents();
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        this.houseDirectory = houseDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        manageCities = new javax.swing.JPanel();
        citySplitPane = new javax.swing.JSplitPane();
        cityControlArea = new javax.swing.JPanel();
        btnUpdateCity = new javax.swing.JButton();
        btnCreateCity = new javax.swing.JButton();
        btnViewCity = new javax.swing.JButton();
        cityWorkArea = new javax.swing.JPanel();
        manageCommunities = new javax.swing.JPanel();
        communitySplitPane = new javax.swing.JSplitPane();
        communityControlArea = new javax.swing.JPanel();
        btnCreateCommunity = new javax.swing.JButton();
        btnViewCommunity = new javax.swing.JButton();
        btnUpdateCommunity = new javax.swing.JButton();
        communityWorkArea = new javax.swing.JPanel();
        manageHouses = new javax.swing.JPanel();
        houseSplitPane = new javax.swing.JSplitPane();
        houseControlArea = new javax.swing.JPanel();
        btnCreateHouse = new javax.swing.JButton();
        btnViewHouse = new javax.swing.JButton();
        btnUpdateHouse = new javax.swing.JButton();
        houseWorkArea = new javax.swing.JPanel();
        lblSystemAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 102));
        tabbedPane.setForeground(new java.awt.Color(0, 0, 255));
        tabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        manageCities.setBackground(new java.awt.Color(255, 255, 153));

        cityControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnUpdateCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateCity.setText("Update");
        btnUpdateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCityActionPerformed(evt);
            }
        });

        btnCreateCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateCity.setText("Create");
        btnCreateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCityActionPerformed(evt);
            }
        });

        btnViewCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewCity.setText("View");
        btnViewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cityControlAreaLayout = new javax.swing.GroupLayout(cityControlArea);
        cityControlArea.setLayout(cityControlAreaLayout);
        cityControlAreaLayout.setHorizontalGroup(
            cityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateCity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewCity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        cityControlAreaLayout.setVerticalGroup(
            cityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateCity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateCity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        citySplitPane.setLeftComponent(cityControlArea);

        cityWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout cityWorkAreaLayout = new javax.swing.GroupLayout(cityWorkArea);
        cityWorkArea.setLayout(cityWorkAreaLayout);
        cityWorkAreaLayout.setHorizontalGroup(
            cityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        cityWorkAreaLayout.setVerticalGroup(
            cityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        citySplitPane.setRightComponent(cityWorkArea);

        javax.swing.GroupLayout manageCitiesLayout = new javax.swing.GroupLayout(manageCities);
        manageCities.setLayout(manageCitiesLayout);
        manageCitiesLayout.setHorizontalGroup(
            manageCitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citySplitPane)
        );
        manageCitiesLayout.setVerticalGroup(
            manageCitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citySplitPane)
        );

        tabbedPane.addTab("Manage Cities", manageCities);

        communitySplitPane.setPreferredSize(new java.awt.Dimension(250, 23));

        communityControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateCommunity.setText("Create");
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });

        btnViewCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewCommunity.setText("View");
        btnViewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunityActionPerformed(evt);
            }
        });

        btnUpdateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateCommunity.setText("Update");
        btnUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout communityControlAreaLayout = new javax.swing.GroupLayout(communityControlArea);
        communityControlArea.setLayout(communityControlAreaLayout);
        communityControlAreaLayout.setHorizontalGroup(
            communityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(communityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        communityControlAreaLayout.setVerticalGroup(
            communityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        communitySplitPane.setLeftComponent(communityControlArea);

        communityWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout communityWorkAreaLayout = new javax.swing.GroupLayout(communityWorkArea);
        communityWorkArea.setLayout(communityWorkAreaLayout);
        communityWorkAreaLayout.setHorizontalGroup(
            communityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        communityWorkAreaLayout.setVerticalGroup(
            communityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        communitySplitPane.setRightComponent(communityWorkArea);

        javax.swing.GroupLayout manageCommunitiesLayout = new javax.swing.GroupLayout(manageCommunities);
        manageCommunities.setLayout(manageCommunitiesLayout);
        manageCommunitiesLayout.setHorizontalGroup(
            manageCommunitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communitySplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        manageCommunitiesLayout.setVerticalGroup(
            manageCommunitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communitySplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Manage Communities", manageCommunities);

        houseControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateHouse.setText("Create");
        btnCreateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHouseActionPerformed(evt);
            }
        });

        btnViewHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewHouse.setText("View");
        btnViewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHouseActionPerformed(evt);
            }
        });

        btnUpdateHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateHouse.setText("Update");
        btnUpdateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout houseControlAreaLayout = new javax.swing.GroupLayout(houseControlArea);
        houseControlArea.setLayout(houseControlAreaLayout);
        houseControlAreaLayout.setHorizontalGroup(
            houseControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(houseControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        houseControlAreaLayout.setVerticalGroup(
            houseControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        houseSplitPane.setLeftComponent(houseControlArea);

        houseWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout houseWorkAreaLayout = new javax.swing.GroupLayout(houseWorkArea);
        houseWorkArea.setLayout(houseWorkAreaLayout);
        houseWorkAreaLayout.setHorizontalGroup(
            houseWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        houseWorkAreaLayout.setVerticalGroup(
            houseWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        houseSplitPane.setRightComponent(houseWorkArea);

        javax.swing.GroupLayout manageHousesLayout = new javax.swing.GroupLayout(manageHouses);
        manageHouses.setLayout(manageHousesLayout);
        manageHousesLayout.setHorizontalGroup(
            manageHousesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(houseSplitPane)
        );
        manageHousesLayout.setVerticalGroup(
            manageHousesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(houseSplitPane)
        );

        tabbedPane.addTab("Manage Houses", manageHouses);

        lblSystemAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblSystemAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSystemAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lblSystemAdmin.setText("                                                                                     Welcome Community Admin!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
            .addComponent(lblSystemAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSystemAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunityActionPerformed
        // TODO add your handling code here:
        viewCommunityJPanel viewCommunity = new viewCommunityJPanel(communityDirectory);
        communitySplitPane.setRightComponent(viewCommunity);
    }//GEN-LAST:event_btnViewCommunityActionPerformed

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        // TODO add your handling code here:
        createCommunityJPanel createCommunity = new createCommunityJPanel(cityDirectory, communityDirectory);
        communitySplitPane.setRightComponent(createCommunity);
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void btnViewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCityActionPerformed
        // TODO add your handling code here:
        viewCityJPanel viewCity = new viewCityJPanel(cityDirectory);
        citySplitPane.setRightComponent(viewCity);
    }//GEN-LAST:event_btnViewCityActionPerformed

    private void btnCreateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCityActionPerformed
        // TODO add your handling code here:
        createCityJPanel createCity = new createCityJPanel(cityDirectory);
        citySplitPane.setRightComponent(createCity);   
    }//GEN-LAST:event_btnCreateCityActionPerformed

    private void btnCreateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHouseActionPerformed
        // TODO add your handling code here:
        createHouseJPanel createHouse = new createHouseJPanel(cityDirectory, communityDirectory, houseDirectory);
        houseSplitPane.setRightComponent(createHouse);
    }//GEN-LAST:event_btnCreateHouseActionPerformed

    private void btnViewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHouseActionPerformed
        // TODO add your handling code here:
        viewHouseJPanel viewHouse = new viewHouseJPanel(houseDirectory);
        houseSplitPane.setRightComponent(viewHouse);
    }//GEN-LAST:event_btnViewHouseActionPerformed

    private void btnUpdateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCityActionPerformed
        // TODO add your handling code here:
        updateCityJPanel updateCity = new updateCityJPanel(cityDirectory);
        citySplitPane.setRightComponent(updateCity);
    }//GEN-LAST:event_btnUpdateCityActionPerformed

    private void btnUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCommunityActionPerformed
        // TODO add your handling code here:
        updateCommunityJPanel updateCommunity = new updateCommunityJPanel(communityDirectory);
        communitySplitPane.setRightComponent(updateCommunity);
    }//GEN-LAST:event_btnUpdateCommunityActionPerformed

    private void btnUpdateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHouseActionPerformed
        // TODO add your handling code here:
        updateHouseJPanel updateHouse = new updateHouseJPanel(houseDirectory);
        houseSplitPane.setRightComponent(updateHouse);
    }//GEN-LAST:event_btnUpdateHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCity;
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnCreateHouse;
    private javax.swing.JButton btnUpdateCity;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JButton btnUpdateHouse;
    private javax.swing.JButton btnViewCity;
    private javax.swing.JButton btnViewCommunity;
    private javax.swing.JButton btnViewHouse;
    private javax.swing.JPanel cityControlArea;
    private javax.swing.JSplitPane citySplitPane;
    private javax.swing.JPanel cityWorkArea;
    private javax.swing.JPanel communityControlArea;
    private javax.swing.JSplitPane communitySplitPane;
    private javax.swing.JPanel communityWorkArea;
    private javax.swing.JPanel houseControlArea;
    private javax.swing.JSplitPane houseSplitPane;
    private javax.swing.JPanel houseWorkArea;
    private javax.swing.JLabel lblSystemAdmin;
    private javax.swing.JPanel manageCities;
    private javax.swing.JPanel manageCommunities;
    private javax.swing.JPanel manageHouses;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
