/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shrey
 */
public class createPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createPatientJPanel
     */
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    
    public createPatientJPanel(CityDirectory cityDirectory, CommunityDirectory communityDirectory, PersonDirectory personDirectory, PatientDirectory patientDirectory) {
        initComponents();
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        txtUID.setEditable(false);
        selectBloodGroup.addItem("A+");
        selectBloodGroup.addItem("A-");
        selectBloodGroup.addItem("B+");
        selectBloodGroup.addItem("B-");
        selectBloodGroup.addItem("O+");
        selectBloodGroup.addItem("O-");
        selectBloodGroup.addItem("AB+");
        selectBloodGroup.addItem("AB-");
        populateCityComboBox(cityDirectory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilterSelect = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewPerson = new javax.swing.JTable();
        lblPassWord = new javax.swing.JLabel();
        selectBloodGroup = new javax.swing.JComboBox<>();
        lblCommunityName = new javax.swing.JLabel();
        selectCommunityCombo = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        txtUID = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        lblCityName = new javax.swing.JLabel();
        txtBodyWeight = new javax.swing.JTextField();
        btnCreatePatient = new javax.swing.JButton();
        lblBloodGroup = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblBodyWeight = new javax.swing.JLabel();
        lblPersonUID = new javax.swing.JLabel();
        selectCityCombo = new javax.swing.JComboBox<>();
        txtPassWord = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 255, 255));

        lblFilterSelect.setBackground(new java.awt.Color(255, 255, 255));
        lblFilterSelect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFilterSelect.setForeground(new java.awt.Color(255, 0, 0));
        lblFilterSelect.setText("                                                                                      Filter and Select a Person");

        tblViewPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Email", "Age", "Phone", "Address", "Community", "City"
            }
        ));
        tblViewPerson.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblViewPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewPersonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblViewPerson);

        lblPassWord.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPassWord.setText("Create Password :");

        selectBloodGroup.setPreferredSize(new java.awt.Dimension(72, 30));
        selectBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBloodGroupActionPerformed(evt);
            }
        });

        lblCommunityName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCommunityName.setText("Select Community : ");

        selectCommunityCombo.setPreferredSize(new java.awt.Dimension(72, 30));
        selectCommunityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCommunityComboActionPerformed(evt);
            }
        });

        btnFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(255, 0, 0));
        btnFilter.setText("Filter");
        btnFilter.setPreferredSize(new java.awt.Dimension(104, 30));
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        txtUID.setPreferredSize(new java.awt.Dimension(72, 22));

        txtUserName.setPreferredSize(new java.awt.Dimension(72, 22));

        lblCityName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCityName.setText("Select City :");

        txtBodyWeight.setPreferredSize(new java.awt.Dimension(72, 22));
        txtBodyWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodyWeightActionPerformed(evt);
            }
        });

        btnCreatePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreatePatient.setForeground(new java.awt.Color(255, 0, 0));
        btnCreatePatient.setText("Create Patient");
        btnCreatePatient.setPreferredSize(new java.awt.Dimension(104, 30));
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        lblBloodGroup.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBloodGroup.setText("Select Blood Group :");

        lblUserName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUserName.setText("Create Username :");

        lblBodyWeight.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBodyWeight.setText("Enter Body Weight :");

        lblPersonUID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonUID.setText("Patient Unique ID :");

        selectCityCombo.setPreferredSize(new java.awt.Dimension(72, 30));
        selectCityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCityComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFilterSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(285, 285, 285)
                                        .addComponent(lblCommunityName)
                                        .addGap(105, 105, 105))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectCommunityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(458, 458, 458)
                                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBodyWeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBloodGroup, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassWord, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPersonUID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBodyWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(txtUID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectBloodGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassWord))
                .addGap(332, 332, 332))
            .addGroup(layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(btnCreatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblFilterSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCommunityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonUID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBloodGroupActionPerformed

    private void selectCommunityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCommunityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCommunityComboActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        String selectedCity = selectCityCombo.getSelectedItem().toString();
        String selectedCommunity = selectCommunityCombo.getSelectedItem().toString();
        populatePersonTable(selectedCity, selectedCommunity);

    }//GEN-LAST:event_btnFilterActionPerformed

    private void txtBodyWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodyWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyWeightActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        Patient p = patientDirectory.addNewPatient(Integer.parseInt(txtUID.getText()), txtUserName.getText(), txtPassWord.getText());
        p.setName(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 0).toString());
        p.setGender(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 1).toString());
        p.setEmailId(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 2).toString());
        p.setAge(Integer.parseInt(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 3).toString()));
        p.setPhoneNumber(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 4).toString());
        p.setHouseAddress(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 5).toString());
        p.setCommunityName(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 6).toString());
        p.setCityName(tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 7).toString());
        p.setPatientBloodGroup(selectBloodGroup.getSelectedItem().toString());
        p.setPatientWeight(Integer.parseInt(txtBodyWeight.getText()));
        
        JOptionPane.showMessageDialog(this, "Patient Created!");
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void tblViewPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewPersonMouseClicked
        // TODO add your handling code here:
        Person p = (Person)tblViewPerson.getValueAt(tblViewPerson.getSelectedRow(), 0);
        txtUID.setText(String.valueOf(p.getPersonId()));
    }//GEN-LAST:event_tblViewPersonMouseClicked

    private void selectCityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCityComboActionPerformed
        // TODO add your handling code here:
        String selectedCity = selectCityCombo.getSelectedItem().toString();
        populateCommunityComboBox(selectedCity);
    }//GEN-LAST:event_selectCityComboActionPerformed

    private void populateCityComboBox(CityDirectory cityDirectory)
    {
        for(City c:cityDirectory.getCityDirectory())
        {
            selectCityCombo.addItem(c.getCityName());
        }
    }
    
    private void populateCommunityComboBox(String selectedCity)
    {
        selectCommunityCombo.removeAllItems();
        for(Community cm:communityDirectory.getCommunityDirectory())
        {
            if(cm.getCityName().equals(selectedCity))
            {
                selectCommunityCombo.addItem(cm.getCommunityName());
            }
        }
    }
    
    private void populatePersonTable(String selectedCity, String selectedCommunity)
    {
        DefaultTableModel model = (DefaultTableModel) tblViewPerson.getModel();
        model.setRowCount(0);
        
        for(Person p:personDirectory.getPersonDirectory())
        {
            if(p.getCityName().equals(selectedCity) && p.getCommunityName().equals(selectedCommunity))
            {
                Object[] row = new Object[8];
                row[0] = p;
                row[1] = p.getGender();
                row[2] = p.getEmailId();
                row[3] = p.getAge();
                row[4] = p.getPhoneNumber();
                row[5] = p.getHouseAddress();
                row[6] = p.getCommunityName();
                row[7] = p.getCityName();
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnFilter;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblBodyWeight;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JLabel lblFilterSelect;
    private javax.swing.JLabel lblPassWord;
    private javax.swing.JLabel lblPersonUID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JComboBox<String> selectBloodGroup;
    private javax.swing.JComboBox<String> selectCityCombo;
    private javax.swing.JComboBox<String> selectCommunityCombo;
    private javax.swing.JTable tblViewPerson;
    private javax.swing.JTextField txtBodyWeight;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
