/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;

/**
 *
 * @author shrey
 */

public class createCommunityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createCityJPanel
     */
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    
    public createCommunityJPanel(CityDirectory cityDirectory, CommunityDirectory communityDirectory) {
        initComponents();
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        populateCityComboBox(cityDirectory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        lblSelectCityName = new javax.swing.JLabel();
        lblCommunityName = new javax.swing.JLabel();
        txtCommunityName = new javax.swing.JTextField();
        lblCreateCommunity = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 255, 255));

        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 51, 51));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        lblSelectCityName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSelectCityName.setText("Select City :");

        lblCommunityName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCommunityName.setText("Enter Community Name :");

        txtCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityNameActionPerformed(evt);
            }
        });

        lblCreateCommunity.setBackground(new java.awt.Color(255, 255, 255));
        lblCreateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateCommunity.setForeground(new java.awt.Color(255, 0, 0));
        lblCreateCommunity.setText("                                                                                          Create Community");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCreateCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCommunityName)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSelectCityName)
                                .addGap(176, 176, 176)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityComboBox, 0, 200, Short.MAX_VALUE)
                            .addComponent(txtCommunityName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCreateCommunity)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        String validate = validationCheck();
        if(!validate.isEmpty())
        {
            JOptionPane.showMessageDialog(this, validate);
        }
        else
        {
            Community newCommunity = communityDirectory.addNewCommunity();
            String selectedCity = cityComboBox.getSelectedItem().toString();
            newCommunity.setCommunityName(txtCommunityName.getText());
            newCommunity.setCityName(selectedCity);
        
            for(City c:cityDirectory.getCityDirectory())
            {
                if(c.getCityName().equals(selectedCity))
                {
                    c.getCityCommunities().add(newCommunity);
                }
            }

            JOptionPane.showMessageDialog(this, "Community Added!");
            txtCommunityName.setText("");
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    
    private void txtCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityNameActionPerformed
    
    private void populateCityComboBox(CityDirectory cityDirectory)
    {
        for(City c:cityDirectory.getCityDirectory())
        {
            cityComboBox.addItem(c.getCityName());
        }
    }
    private String validationCheck()
    {
        if(txtCommunityName.getText().isEmpty())
        {
            return "Please fill all fields!";
        }
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JLabel lblCreateCommunity;
    private javax.swing.JLabel lblSelectCityName;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField txtCommunityName;
    // End of variables declaration//GEN-END:variables
}
