/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.House;
import model.HouseDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shrey
 */
public class createPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createPersonJPanel
     */
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    HouseDirectory houseDirectory;
    PersonDirectory personDirectory;
    
    public createPersonJPanel(CityDirectory cityDirectory, CommunityDirectory communityDirectory, HouseDirectory houseDirectory,
    PersonDirectory personDirectory) {
        initComponents();
        this.communityDirectory = communityDirectory;
        this.cityDirectory = cityDirectory;
        this.houseDirectory = houseDirectory;
        this.personDirectory = personDirectory;
        populateCityComboBox(cityDirectory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreatePerson = new javax.swing.JLabel();
        lblSelectHouse = new javax.swing.JLabel();
        selectHouseCombo = new javax.swing.JComboBox<>();
        lblSelectCommunity = new javax.swing.JLabel();
        selectCommunityCombo = new javax.swing.JComboBox<>();
        selectCityCombo = new javax.swing.JComboBox<>();
        lblSelectCity = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblPersonGender = new javax.swing.JLabel();
        lblPersonAge = new javax.swing.JLabel();
        lblPersonPhoneNumber = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        lblPersonEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 255));

        lblCreatePerson.setBackground(new java.awt.Color(255, 255, 255));
        lblCreatePerson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreatePerson.setForeground(new java.awt.Color(255, 0, 0));
        lblCreatePerson.setText("                                                     Create Person");

        lblSelectHouse.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSelectHouse.setText("Select House :");

        selectHouseCombo.setPreferredSize(new java.awt.Dimension(72, 30));
        selectHouseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectHouseComboActionPerformed(evt);
            }
        });

        lblSelectCommunity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSelectCommunity.setText("Select Community : ");

        selectCommunityCombo.setPreferredSize(new java.awt.Dimension(72, 30));
        selectCommunityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCommunityComboActionPerformed(evt);
            }
        });

        selectCityCombo.setPreferredSize(new java.awt.Dimension(72, 30));
        selectCityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCityComboActionPerformed(evt);
            }
        });

        lblSelectCity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSelectCity.setText("Select City :");

        lblPersonName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonName.setText("Enter Name :");

        lblPersonGender.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonGender.setText("Enter Gender :");

        lblPersonAge.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonAge.setText("Enter Age :");

        lblPersonPhoneNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonPhoneNumber.setText("Enter Phone Number :");

        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 51, 51));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        txtGender.setPreferredSize(new java.awt.Dimension(71, 30));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtAge.setPreferredSize(new java.awt.Dimension(71, 30));

        txtPhoneNumber.setPreferredSize(new java.awt.Dimension(71, 30));

        txtName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtEmailId.setPreferredSize(new java.awt.Dimension(71, 30));
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        lblPersonEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonEmail.setText("Enter Email Id :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(603, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSelectHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPersonGender, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPersonAge, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblSelectCity, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(232, 232, 232))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPersonPhoneNumber)
                                    .addComponent(lblSelectCommunity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectCommunityCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectHouseCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCommunityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectHouseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblPersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersonGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectHouseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectHouseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectHouseComboActionPerformed

    private void selectCommunityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCommunityComboActionPerformed
        // TODO add your handling code here:
        try
        {
            String selectedCommunity = selectCommunityCombo.getSelectedItem().toString();
            populateHouseComboBox(selectedCommunity);
        }catch(NullPointerException e)
        {}
        
    }//GEN-LAST:event_selectCommunityComboActionPerformed

    private void selectCityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCityComboActionPerformed
        // TODO add your handling code here:
        try
        {
            String selectedCity = selectCityCombo.getSelectedItem().toString();
            populateCommunityComboBox(selectedCity);
        }catch(NullPointerException e)
        {}
    }//GEN-LAST:event_selectCityComboActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
           
        String validate = validationCheck();
        if(!validate.isEmpty())
        {
            JOptionPane.showMessageDialog(this, validate);
        }
        else
        {
            Person newPerson = personDirectory.addNewPerson();
            String selectedCity = selectCityCombo.getSelectedItem().toString();
            String selectedCommunity = selectCommunityCombo.getSelectedItem().toString();
            String selectedHouseAddress = selectHouseCombo.getSelectedItem().toString();

            newPerson.setCityName(selectedCity);
            newPerson.setCommunityName(selectedCommunity);
            newPerson.setHouseAddress(selectedHouseAddress);
            newPerson.setAge(Integer.parseInt(txtAge.getText()));
            newPerson.setEmailId(txtEmailId.getText());
            newPerson.setGender(txtGender.getText());
            newPerson.setName(txtName.getText());
            newPerson.setPhoneNumber(txtPhoneNumber.getText());

            for(House h:houseDirectory.getHouseDirectory())
            {
                if(h.getStreetAddress().equals(selectedHouseAddress))
                {
                    h.getResidents().add(newPerson);
                }
            }

            JOptionPane.showMessageDialog(this, "Person Added!");
            txtAge.setText("");
            txtEmailId.setText("");
            txtGender.setText("");
            txtName.setText("");
            txtPhoneNumber.setText("");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed
    
    private void populateCityComboBox(CityDirectory cityDirectory)
    {
        for(City c:cityDirectory.getCityDirectory())
        {
            selectCityCombo.addItem(c.getCityName());
        }
    }
    
    private void populateCommunityComboBox(String selectedCity)
    {
        selectCommunityCombo.removeAllItems();
        selectHouseCombo.removeAllItems();
        for(Community cm:communityDirectory.getCommunityDirectory())
        {
            if(cm.getCityName().equals(selectedCity))
            {
                selectCommunityCombo.addItem(cm.getCommunityName());
            }
        }
    }
    
    private void populateHouseComboBox(String selectedCommunity)
    {
        selectHouseCombo.removeAllItems();
        for(House h:houseDirectory.getHouseDirectory())
        {
            if(h.getCommunityName().equals(selectedCommunity))
            {
                selectHouseCombo.addItem(h.getStreetAddress());
            }
        }
    }
    
    private String validationCheck()
    {
        if(txtName.getText().isEmpty() || txtGender.getText().isEmpty() || txtEmailId.getText().isEmpty() || txtPhoneNumber.getText().isEmpty() || txtAge.getText().isEmpty())
        {
            return "Please fill all fields!";
        }
        try
        {
            int age = Integer.parseInt(txtAge.getText());
        }
        catch(NumberFormatException ex)
        {
            return "Age has to be a Number!";
        }
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCreatePerson;
    private javax.swing.JLabel lblPersonAge;
    private javax.swing.JLabel lblPersonEmail;
    private javax.swing.JLabel lblPersonGender;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblPersonPhoneNumber;
    private javax.swing.JLabel lblSelectCity;
    private javax.swing.JLabel lblSelectCommunity;
    private javax.swing.JLabel lblSelectHouse;
    private javax.swing.JComboBox<String> selectCityCombo;
    private javax.swing.JComboBox<String> selectCommunityCombo;
    private javax.swing.JComboBox<String> selectHouseCombo;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
