/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterDirectory;
import model.HospitalDirectory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author shrey
 */

public class hospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdmin
     */
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    HospitalDirectory hospitalDirectory;
    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    DoctorDirectory doctorDirectory;
    EncounterDirectory ecounterDirectory;
    
    public hospitalAdminJPanel(CityDirectory cityDirectory, CommunityDirectory communityDirectory, HospitalDirectory hospitalDirectory, PatientDirectory patientDirectory, PersonDirectory personDirectory, DoctorDirectory doctorDirectory, EncounterDirectory ecounterDirectory) throws Exception {
        initComponents();
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.patientDirectory = patientDirectory;
        this.personDirectory = personDirectory;
        this.doctorDirectory = doctorDirectory;
        this.ecounterDirectory = ecounterDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        manageHospitals = new javax.swing.JPanel();
        hospitalSplitPane = new javax.swing.JSplitPane();
        hospitalControlArea = new javax.swing.JPanel();
        btnCreateHospital = new javax.swing.JButton();
        btnViewHospital = new javax.swing.JButton();
        btnUpdateHospital = new javax.swing.JButton();
        hospitalWorkArea = new javax.swing.JPanel();
        managePatientsDoctors = new javax.swing.JPanel();
        patientsDoctorsSplitPane = new javax.swing.JSplitPane();
        patientsDoctorsControlArea = new javax.swing.JPanel();
        btnUpdatePatient = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnUpdateDoctor = new javax.swing.JButton();
        btnCreatePatient = new javax.swing.JButton();
        btnViewDoctor = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        lblPatientsDoctors = new javax.swing.JLabel();
        patientsDoctorsWorkArea = new javax.swing.JPanel();
        manageEncounters = new javax.swing.JPanel();
        encounterSplitPane = new javax.swing.JSplitPane();
        encounterControlArea = new javax.swing.JPanel();
        btnCreateEncounter = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        btnUpdateEncounter = new javax.swing.JButton();
        encounterWorkArea = new javax.swing.JPanel();
        lblSystemAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 102));
        tabbedPane.setForeground(new java.awt.Color(0, 0, 255));
        tabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        hospitalControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateHospital.setText("Create");
        btnCreateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalActionPerformed(evt);
            }
        });

        btnViewHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewHospital.setText("View");
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });

        btnUpdateHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateHospital.setText("Update");
        btnUpdateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hospitalControlAreaLayout = new javax.swing.GroupLayout(hospitalControlArea);
        hospitalControlArea.setLayout(hospitalControlAreaLayout);
        hospitalControlAreaLayout.setHorizontalGroup(
            hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        hospitalControlAreaLayout.setVerticalGroup(
            hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        hospitalSplitPane.setLeftComponent(hospitalControlArea);

        hospitalWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout hospitalWorkAreaLayout = new javax.swing.GroupLayout(hospitalWorkArea);
        hospitalWorkArea.setLayout(hospitalWorkAreaLayout);
        hospitalWorkAreaLayout.setHorizontalGroup(
            hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        hospitalWorkAreaLayout.setVerticalGroup(
            hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        hospitalSplitPane.setRightComponent(hospitalWorkArea);

        javax.swing.GroupLayout manageHospitalsLayout = new javax.swing.GroupLayout(manageHospitals);
        manageHospitals.setLayout(manageHospitalsLayout);
        manageHospitalsLayout.setHorizontalGroup(
            manageHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalSplitPane)
        );
        manageHospitalsLayout.setVerticalGroup(
            manageHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalSplitPane)
        );

        tabbedPane.addTab("Hospitals", manageHospitals);

        patientsDoctorsSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        patientsDoctorsControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnUpdatePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdatePatient.setText("Update");
        btnUpdatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientActionPerformed(evt);
            }
        });

        btnCreateDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateDoctor.setText("Create");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        btnUpdateDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateDoctor.setText("Update");
        btnUpdateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDoctorActionPerformed(evt);
            }
        });

        btnCreatePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreatePatient.setText("Create");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnViewDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewDoctor.setText("View");
        btnViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorActionPerformed(evt);
            }
        });

        btnViewPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewPatient.setText("View");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        lblPatientsDoctors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPatientsDoctors.setForeground(new java.awt.Color(255, 0, 0));
        lblPatientsDoctors.setText("                                   Patients                                                                                                                                    Doctors");

        javax.swing.GroupLayout patientsDoctorsControlAreaLayout = new javax.swing.GroupLayout(patientsDoctorsControlArea);
        patientsDoctorsControlArea.setLayout(patientsDoctorsControlAreaLayout);
        patientsDoctorsControlAreaLayout.setHorizontalGroup(
            patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientsDoctorsControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientsDoctorsControlAreaLayout.createSequentialGroup()
                        .addComponent(btnCreatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(btnViewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnUpdatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(259, 259, 259)
                        .addComponent(btnCreateDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(btnViewDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(btnUpdateDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(133, 133, 133))
                    .addGroup(patientsDoctorsControlAreaLayout.createSequentialGroup()
                        .addComponent(lblPatientsDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        patientsDoctorsControlAreaLayout.setVerticalGroup(
            patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientsDoctorsControlAreaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPatientsDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        patientsDoctorsSplitPane.setTopComponent(patientsDoctorsControlArea);

        patientsDoctorsWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout patientsDoctorsWorkAreaLayout = new javax.swing.GroupLayout(patientsDoctorsWorkArea);
        patientsDoctorsWorkArea.setLayout(patientsDoctorsWorkAreaLayout);
        patientsDoctorsWorkAreaLayout.setHorizontalGroup(
            patientsDoctorsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        patientsDoctorsWorkAreaLayout.setVerticalGroup(
            patientsDoctorsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        patientsDoctorsSplitPane.setRightComponent(patientsDoctorsWorkArea);

        javax.swing.GroupLayout managePatientsDoctorsLayout = new javax.swing.GroupLayout(managePatientsDoctors);
        managePatientsDoctors.setLayout(managePatientsDoctorsLayout);
        managePatientsDoctorsLayout.setHorizontalGroup(
            managePatientsDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientsDoctorsSplitPane)
        );
        managePatientsDoctorsLayout.setVerticalGroup(
            managePatientsDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientsDoctorsSplitPane)
        );

        tabbedPane.addTab("Patients & Doctors", managePatientsDoctors);

        encounterControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateEncounter.setText("Create");
        btnCreateEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEncounterActionPerformed(evt);
            }
        });

        btnViewEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewEncounter.setText("View");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        btnUpdateEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateEncounter.setText("Update");

        javax.swing.GroupLayout encounterControlAreaLayout = new javax.swing.GroupLayout(encounterControlArea);
        encounterControlArea.setLayout(encounterControlAreaLayout);
        encounterControlAreaLayout.setHorizontalGroup(
            encounterControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encounterControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        encounterControlAreaLayout.setVerticalGroup(
            encounterControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        encounterSplitPane.setLeftComponent(encounterControlArea);

        encounterWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout encounterWorkAreaLayout = new javax.swing.GroupLayout(encounterWorkArea);
        encounterWorkArea.setLayout(encounterWorkAreaLayout);
        encounterWorkAreaLayout.setHorizontalGroup(
            encounterWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        encounterWorkAreaLayout.setVerticalGroup(
            encounterWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        encounterSplitPane.setRightComponent(encounterWorkArea);

        javax.swing.GroupLayout manageEncountersLayout = new javax.swing.GroupLayout(manageEncounters);
        manageEncounters.setLayout(manageEncountersLayout);
        manageEncountersLayout.setHorizontalGroup(
            manageEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encounterSplitPane)
        );
        manageEncountersLayout.setVerticalGroup(
            manageEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encounterSplitPane)
        );

        tabbedPane.addTab("Encounters", manageEncounters);

        lblSystemAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblSystemAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSystemAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lblSystemAdmin.setText("                                                                              Welcome Hospital Admin!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
            .addComponent(lblSystemAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
        viewHospitalJPanel viewHospital = new viewHospitalJPanel(hospitalDirectory);
        hospitalSplitPane.setRightComponent(viewHospital);
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnCreateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalActionPerformed
        // TODO add your handling code here:
        createHospitalJPanel createHospital = new createHospitalJPanel(cityDirectory, communityDirectory, hospitalDirectory);
        hospitalSplitPane.setRightComponent(createHospital);     
    }//GEN-LAST:event_btnCreateHospitalActionPerformed

    private void btnCreateEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEncounterActionPerformed
        // TODO add your handling code here:
        createEncounters encounters = new createEncounters(patientDirectory, ecounterDirectory, hospitalDirectory);
        encounterSplitPane.setRightComponent(encounters);
    }//GEN-LAST:event_btnCreateEncounterActionPerformed

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        viewAllEncounters encounters = new viewAllEncounters(ecounterDirectory, patientDirectory);
        encounterSplitPane.setRightComponent(encounters);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    private void btnUpdatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePatientActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        createDoctorJPanel createDoctor = new createDoctorJPanel(cityDirectory, communityDirectory, personDirectory, doctorDirectory, hospitalDirectory);
        patientsDoctorsSplitPane.setBottomComponent(createDoctor);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnUpdateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateDoctorActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        createPatientJPanel createPatient = new createPatientJPanel(cityDirectory, communityDirectory, personDirectory, patientDirectory);
        patientsDoctorsSplitPane.setBottomComponent(createPatient);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorActionPerformed
        // TODO add your handling code here:
        viewDoctorJPanel viewDoctor = new viewDoctorJPanel(doctorDirectory);
        patientsDoctorsSplitPane.setBottomComponent(viewDoctor);
    }//GEN-LAST:event_btnViewDoctorActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        viewPatientJPanel viewPatient = new viewPatientJPanel(patientDirectory);
        patientsDoctorsSplitPane.setBottomComponent(viewPatient);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnUpdateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHospitalActionPerformed
        // TODO add your handling code here:
        updateHospitalJPanel updateHospital = new updateHospitalJPanel(hospitalDirectory);
        hospitalSplitPane.setRightComponent(updateHospital);
    }//GEN-LAST:event_btnUpdateHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreateEncounter;
    private javax.swing.JButton btnCreateHospital;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnUpdateDoctor;
    private javax.swing.JButton btnUpdateEncounter;
    private javax.swing.JButton btnUpdateHospital;
    private javax.swing.JButton btnUpdatePatient;
    private javax.swing.JButton btnViewDoctor;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JPanel encounterControlArea;
    private javax.swing.JSplitPane encounterSplitPane;
    private javax.swing.JPanel encounterWorkArea;
    private javax.swing.JPanel hospitalControlArea;
    private javax.swing.JSplitPane hospitalSplitPane;
    private javax.swing.JPanel hospitalWorkArea;
    private javax.swing.JLabel lblPatientsDoctors;
    private javax.swing.JLabel lblSystemAdmin;
    private javax.swing.JPanel manageEncounters;
    private javax.swing.JPanel manageHospitals;
    private javax.swing.JPanel managePatientsDoctors;
    private javax.swing.JPanel patientsDoctorsControlArea;
    private javax.swing.JSplitPane patientsDoctorsSplitPane;
    private javax.swing.JPanel patientsDoctorsWorkArea;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
