/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author shrey
 */
public class hospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdmin
     */
    public hospitalAdminJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        manageDoctors = new javax.swing.JPanel();
        hospitalSplitPane = new javax.swing.JSplitPane();
        hospitalWorkArea = new javax.swing.JPanel();
        createHospitalButton = new javax.swing.JButton();
        readHospitalButton = new javax.swing.JButton();
        updateHospitalButton = new javax.swing.JButton();
        deleteHospitalButton = new javax.swing.JButton();
        hospitalControlArea = new javax.swing.JPanel();
        managePatients = new javax.swing.JPanel();

        createHospitalButton.setText("Create");
        createHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHospitalButtonActionPerformed(evt);
            }
        });

        readHospitalButton.setText("Read");

        updateHospitalButton.setText("Update");
        updateHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHospitalButtonActionPerformed(evt);
            }
        });

        deleteHospitalButton.setText("Delete");

        javax.swing.GroupLayout hospitalWorkAreaLayout = new javax.swing.GroupLayout(hospitalWorkArea);
        hospitalWorkArea.setLayout(hospitalWorkAreaLayout);
        hospitalWorkAreaLayout.setHorizontalGroup(
            hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalWorkAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createHospitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readHospitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateHospitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteHospitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        hospitalWorkAreaLayout.setVerticalGroup(
            hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalWorkAreaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(createHospitalButton)
                .addGap(32, 32, 32)
                .addComponent(readHospitalButton)
                .addGap(30, 30, 30)
                .addComponent(updateHospitalButton)
                .addGap(30, 30, 30)
                .addComponent(deleteHospitalButton)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        hospitalSplitPane.setLeftComponent(hospitalWorkArea);

        javax.swing.GroupLayout hospitalControlAreaLayout = new javax.swing.GroupLayout(hospitalControlArea);
        hospitalControlArea.setLayout(hospitalControlAreaLayout);
        hospitalControlAreaLayout.setHorizontalGroup(
            hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        hospitalControlAreaLayout.setVerticalGroup(
            hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        hospitalSplitPane.setRightComponent(hospitalControlArea);

        javax.swing.GroupLayout manageDoctorsLayout = new javax.swing.GroupLayout(manageDoctors);
        manageDoctors.setLayout(manageDoctorsLayout);
        manageDoctorsLayout.setHorizontalGroup(
            manageDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalSplitPane)
        );
        manageDoctorsLayout.setVerticalGroup(
            manageDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalSplitPane)
        );

        tabbedPane.addTab("Manage Doctors", manageDoctors);

        javax.swing.GroupLayout managePatientsLayout = new javax.swing.GroupLayout(managePatients);
        managePatients.setLayout(managePatientsLayout);
        managePatientsLayout.setHorizontalGroup(
            managePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        managePatientsLayout.setVerticalGroup(
            managePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Manage Patients", managePatients);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHospitalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateHospitalButtonActionPerformed

    private void createHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHospitalButtonActionPerformed
        // TODO add your handling code here:
        createHospitalJPanel hospital = new createHospitalJPanel();
        hospitalSplitPane.setRightComponent(hospital);

    }//GEN-LAST:event_createHospitalButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createHospitalButton;
    private javax.swing.JButton deleteHospitalButton;
    private javax.swing.JPanel hospitalControlArea;
    private javax.swing.JSplitPane hospitalSplitPane;
    private javax.swing.JPanel hospitalWorkArea;
    private javax.swing.JPanel manageDoctors;
    private javax.swing.JPanel managePatients;
    private javax.swing.JButton readHospitalButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JButton updateHospitalButton;
    // End of variables declaration//GEN-END:variables
}
