/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.IOException;

import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterDirectory;
import model.HospitalDirectory;
import model.Patient;
import model.PersonDirectory;

/**
 *
 * @author shrey
 */

public class patientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdmin
     */
    Patient p;
    PersonDirectory personDirectory;
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospitalDirectory;
    EncounterDirectory encounterDirectory;
    
    public patientJPanel(Patient p, PersonDirectory personDirectory, CityDirectory cityDirectory, CommunityDirectory communityDirectory, DoctorDirectory doctorDirectory, HospitalDirectory hospitalDirectory, EncounterDirectory encounterDirectory) throws IOException {
        initComponents(); 
        this.p = p;
        this.personDirectory = personDirectory;
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        this.doctorDirectory = doctorDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.encounterDirectory = encounterDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        personalDetails = new javax.swing.JPanel();
        personalDetailSplitPane = new javax.swing.JSplitPane();
        personalDetailsControlArea = new javax.swing.JPanel();
        btnViewDetails = new javax.swing.JButton();
        btnUpdateDetails = new javax.swing.JButton();
        personalDetailsWorkArea = new javax.swing.JPanel();
        personalEncounters = new javax.swing.JPanel();
        encountersSplitPane = new javax.swing.JSplitPane();
        encountersControlArea = new javax.swing.JPanel();
        btnCreateEncounter = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        encountersWorkArea = new javax.swing.JPanel();
        searchDoctors = new javax.swing.JPanel();
        searchDoctorsSplitPane = new javax.swing.JSplitPane();
        searchControlArea = new javax.swing.JPanel();
        btnSearchDoctors = new javax.swing.JButton();
        searchWorkArea = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 102));
        tabbedPane.setForeground(new java.awt.Color(0, 0, 255));
        tabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        personalDetails.setBackground(new java.awt.Color(0, 255, 255));

        personalDetailsControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnViewDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewDetails.setText("View");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnUpdateDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateDetails.setText("Update");
        btnUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personalDetailsControlAreaLayout = new javax.swing.GroupLayout(personalDetailsControlArea);
        personalDetailsControlArea.setLayout(personalDetailsControlAreaLayout);
        personalDetailsControlAreaLayout.setHorizontalGroup(
            personalDetailsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(personalDetailsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personalDetailsControlAreaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(personalDetailsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUpdateDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        personalDetailsControlAreaLayout.setVerticalGroup(
            personalDetailsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(personalDetailsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personalDetailsControlAreaLayout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnUpdateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );

        personalDetailSplitPane.setLeftComponent(personalDetailsControlArea);

        personalDetailsWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout personalDetailsWorkAreaLayout = new javax.swing.GroupLayout(personalDetailsWorkArea);
        personalDetailsWorkArea.setLayout(personalDetailsWorkAreaLayout);
        personalDetailsWorkAreaLayout.setHorizontalGroup(
            personalDetailsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        personalDetailsWorkAreaLayout.setVerticalGroup(
            personalDetailsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        personalDetailSplitPane.setRightComponent(personalDetailsWorkArea);

        javax.swing.GroupLayout personalDetailsLayout = new javax.swing.GroupLayout(personalDetails);
        personalDetails.setLayout(personalDetailsLayout);
        personalDetailsLayout.setHorizontalGroup(
            personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalDetailSplitPane)
        );
        personalDetailsLayout.setVerticalGroup(
            personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalDetailSplitPane)
        );

        tabbedPane.addTab("Details", personalDetails);

        encountersSplitPane.setPreferredSize(new java.awt.Dimension(250, 23));

        encountersControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateEncounter.setText("Create");
        btnCreateEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEncounterActionPerformed(evt);
            }
        });

        btnViewEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewEncounter.setText("View");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout encountersControlAreaLayout = new javax.swing.GroupLayout(encountersControlArea);
        encountersControlArea.setLayout(encountersControlAreaLayout);
        encountersControlAreaLayout.setHorizontalGroup(
            encountersControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encountersControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encountersControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateEncounter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        encountersControlAreaLayout.setVerticalGroup(
            encountersControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encountersControlAreaLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnCreateEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnViewEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        encountersSplitPane.setLeftComponent(encountersControlArea);

        encountersWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout encountersWorkAreaLayout = new javax.swing.GroupLayout(encountersWorkArea);
        encountersWorkArea.setLayout(encountersWorkAreaLayout);
        encountersWorkAreaLayout.setHorizontalGroup(
            encountersWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        encountersWorkAreaLayout.setVerticalGroup(
            encountersWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        encountersSplitPane.setRightComponent(encountersWorkArea);

        javax.swing.GroupLayout personalEncountersLayout = new javax.swing.GroupLayout(personalEncounters);
        personalEncounters.setLayout(personalEncountersLayout);
        personalEncountersLayout.setHorizontalGroup(
            personalEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encountersSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        personalEncountersLayout.setVerticalGroup(
            personalEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encountersSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Encounters", personalEncounters);

        searchControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnSearchDoctors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchDoctors.setText("Search");
        btnSearchDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDoctorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchControlAreaLayout = new javax.swing.GroupLayout(searchControlArea);
        searchControlArea.setLayout(searchControlAreaLayout);
        searchControlAreaLayout.setHorizontalGroup(
            searchControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchControlAreaLayout.setVerticalGroup(
            searchControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchControlAreaLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnSearchDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        searchDoctorsSplitPane.setLeftComponent(searchControlArea);

        searchWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout searchWorkAreaLayout = new javax.swing.GroupLayout(searchWorkArea);
        searchWorkArea.setLayout(searchWorkAreaLayout);
        searchWorkAreaLayout.setHorizontalGroup(
            searchWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        searchWorkAreaLayout.setVerticalGroup(
            searchWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        searchDoctorsSplitPane.setRightComponent(searchWorkArea);

        javax.swing.GroupLayout searchDoctorsLayout = new javax.swing.GroupLayout(searchDoctors);
        searchDoctors.setLayout(searchDoctorsLayout);
        searchDoctorsLayout.setHorizontalGroup(
            searchDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchDoctorsSplitPane)
        );
        searchDoctorsLayout.setVerticalGroup(
            searchDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchDoctorsSplitPane)
        );

        tabbedPane.addTab("Search Doctors", searchDoctors);

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 0, 0));
        lblWelcome.setText("                                                                                        Welcome !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
            .addComponent(lblWelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        viewPersonalEncounters viewEncounter = new viewPersonalEncounters(p);
        encountersSplitPane.setRightComponent(viewEncounter);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    private void btnCreateEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEncounterActionPerformed
        // TODO add your handling code here:
        createPersonalEncounters createEncounter = new createPersonalEncounters(p, encounterDirectory, hospitalDirectory);
        encountersSplitPane.setRightComponent(createEncounter);
    }//GEN-LAST:event_btnCreateEncounterActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        viewPersonalDetails viewDetails = new viewPersonalDetails(p);
        personalDetailSplitPane.setRightComponent(viewDetails);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDetailsActionPerformed
        // TODO add your handling code here:
        updatePatientDetails updateDetails =  new updatePatientDetails(p, personDirectory);
        personalDetailSplitPane.setRightComponent(updateDetails);
    }//GEN-LAST:event_btnUpdateDetailsActionPerformed

    private void btnSearchDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDoctorsActionPerformed
        // TODO add your handling code here:
        searchNearDoctors searchDoctors =  new searchNearDoctors(cityDirectory, communityDirectory, doctorDirectory);
        searchDoctorsSplitPane.setRightComponent(searchDoctors);
    }//GEN-LAST:event_btnSearchDoctorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEncounter;
    private javax.swing.JButton btnSearchDoctors;
    private javax.swing.JButton btnUpdateDetails;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JPanel encountersControlArea;
    private javax.swing.JSplitPane encountersSplitPane;
    private javax.swing.JPanel encountersWorkArea;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JSplitPane personalDetailSplitPane;
    private javax.swing.JPanel personalDetails;
    private javax.swing.JPanel personalDetailsControlArea;
    private javax.swing.JPanel personalDetailsWorkArea;
    private javax.swing.JPanel personalEncounters;
    private javax.swing.JPanel searchControlArea;
    private javax.swing.JPanel searchDoctors;
    private javax.swing.JSplitPane searchDoctorsSplitPane;
    private javax.swing.JPanel searchWorkArea;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
