/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterDirectory;
import model.HospitalDirectory;
import model.HouseDirectory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author shrey
 */

public class systemAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdmin
     */
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    HospitalDirectory hospitalDirectory;
    HouseDirectory houseDirectory;
    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    DoctorDirectory doctorDirectory;
    EncounterDirectory ecounterDirectory;
    
    public systemAdminJPanel(CityDirectory cityDirectory, CommunityDirectory communityDirectory, HospitalDirectory hospitalDirectory, HouseDirectory houseDirectory, PatientDirectory patientDirectory,
    PersonDirectory personDirectory, DoctorDirectory doctorDirectory, EncounterDirectory ecounterDirectory) throws IOException {
        initComponents();
        URL urlInput = new URL("https://i.postimg.cc/vmq8jXq9/city.jpg");
        BufferedImage image = ImageIO.read(urlInput);
        Image resultingImage = image.getScaledInstance(807, 388, Image.SCALE_DEFAULT);
        jLabel1.setIcon(new ImageIcon(resultingImage));
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.houseDirectory = houseDirectory;
        this.patientDirectory = patientDirectory;
        this.personDirectory = personDirectory;
        this.doctorDirectory = doctorDirectory;
        this.ecounterDirectory = ecounterDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        manageCities = new javax.swing.JPanel();
        citySplitPane = new javax.swing.JSplitPane();
        cityControlArea = new javax.swing.JPanel();
        btnDeleteCity = new javax.swing.JButton();
        btnUpdateCity = new javax.swing.JButton();
        btnCreateCity = new javax.swing.JButton();
        btnViewCity = new javax.swing.JButton();
        cityWorkArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageCommunities = new javax.swing.JPanel();
        communitySplitPane = new javax.swing.JSplitPane();
        communityControlArea = new javax.swing.JPanel();
        btnCreateCommunity = new javax.swing.JButton();
        btnViewCommunity = new javax.swing.JButton();
        btnUpdateCommunity = new javax.swing.JButton();
        btnDeleteCommunity = new javax.swing.JButton();
        communityWorkArea = new javax.swing.JPanel();
        manageHospitals = new javax.swing.JPanel();
        hospitalSplitPane = new javax.swing.JSplitPane();
        hospitalControlArea = new javax.swing.JPanel();
        btnCreateHospital = new javax.swing.JButton();
        btnViewHospital = new javax.swing.JButton();
        btnUpdateHospital = new javax.swing.JButton();
        btnDeleteHospital = new javax.swing.JButton();
        hospitalWorkArea = new javax.swing.JPanel();
        manageHouses = new javax.swing.JPanel();
        houseSplitPane = new javax.swing.JSplitPane();
        houseControlArea = new javax.swing.JPanel();
        btnCreateHouse = new javax.swing.JButton();
        btnViewHouse = new javax.swing.JButton();
        btnUpdateHospital1 = new javax.swing.JButton();
        btnDeleteHouse = new javax.swing.JButton();
        houseWorkArea = new javax.swing.JPanel();
        managePeople = new javax.swing.JPanel();
        peopleSplitPane = new javax.swing.JSplitPane();
        peopleControlArea = new javax.swing.JPanel();
        btnCreatePeople = new javax.swing.JButton();
        btnViewPeople = new javax.swing.JButton();
        btnUpdatePeople = new javax.swing.JButton();
        btnDeletePeople = new javax.swing.JButton();
        peopleWorkArea = new javax.swing.JPanel();
        managePatientsDoctors = new javax.swing.JPanel();
        patientsDoctorsSplitPane = new javax.swing.JSplitPane();
        patientsDoctorsControlArea = new javax.swing.JPanel();
        btnUpdatePatient = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnUpdateDoctor = new javax.swing.JButton();
        btnDeletePatient = new javax.swing.JButton();
        btnDeleteDoctor = new javax.swing.JButton();
        btnCreatePatient = new javax.swing.JButton();
        btnViewDoctor = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        lblPatientsDoctors = new javax.swing.JLabel();
        patientsDoctorsWorkArea = new javax.swing.JPanel();
        manageEncounters = new javax.swing.JPanel();
        encounterSplitPane = new javax.swing.JSplitPane();
        encounterControlArea = new javax.swing.JPanel();
        btnCreateEncounter = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        btnUpdateEncounter = new javax.swing.JButton();
        btnDeleteEncounter = new javax.swing.JButton();
        encounterWorkArea = new javax.swing.JPanel();
        lblSystemAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 102));
        tabbedPane.setForeground(new java.awt.Color(0, 0, 255));
        tabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        manageCities.setBackground(new java.awt.Color(255, 255, 153));

        cityControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnDeleteCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteCity.setText("Delete");
        btnDeleteCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCityActionPerformed(evt);
            }
        });

        btnUpdateCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateCity.setText("Update");

        btnCreateCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateCity.setText("Create");
        btnCreateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCityActionPerformed(evt);
            }
        });

        btnViewCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewCity.setText("View");
        btnViewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cityControlAreaLayout = new javax.swing.GroupLayout(cityControlArea);
        cityControlArea.setLayout(cityControlAreaLayout);
        cityControlAreaLayout.setHorizontalGroup(
            cityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCity, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnDeleteCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnCreateCity, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnViewCity, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        cityControlAreaLayout.setVerticalGroup(
            cityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateCity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateCity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteCity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        citySplitPane.setLeftComponent(cityControlArea);

        cityWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout cityWorkAreaLayout = new javax.swing.GroupLayout(cityWorkArea);
        cityWorkArea.setLayout(cityWorkAreaLayout);
        cityWorkAreaLayout.setHorizontalGroup(
            cityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityWorkAreaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        cityWorkAreaLayout.setVerticalGroup(
            cityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityWorkAreaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        citySplitPane.setRightComponent(cityWorkArea);

        javax.swing.GroupLayout manageCitiesLayout = new javax.swing.GroupLayout(manageCities);
        manageCities.setLayout(manageCitiesLayout);
        manageCitiesLayout.setHorizontalGroup(
            manageCitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citySplitPane)
        );
        manageCitiesLayout.setVerticalGroup(
            manageCitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citySplitPane)
        );

        tabbedPane.addTab("Cities", manageCities);

        communitySplitPane.setPreferredSize(new java.awt.Dimension(250, 23));

        communityControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateCommunity.setText("Create");
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });

        btnViewCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewCommunity.setText("View");
        btnViewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunityActionPerformed(evt);
            }
        });

        btnUpdateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateCommunity.setText("Update");

        btnDeleteCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteCommunity.setText("Delete");
        btnDeleteCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout communityControlAreaLayout = new javax.swing.GroupLayout(communityControlArea);
        communityControlArea.setLayout(communityControlAreaLayout);
        communityControlAreaLayout.setHorizontalGroup(
            communityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(communityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDeleteCommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        communityControlAreaLayout.setVerticalGroup(
            communityControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        communitySplitPane.setLeftComponent(communityControlArea);

        communityWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout communityWorkAreaLayout = new javax.swing.GroupLayout(communityWorkArea);
        communityWorkArea.setLayout(communityWorkAreaLayout);
        communityWorkAreaLayout.setHorizontalGroup(
            communityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        communityWorkAreaLayout.setVerticalGroup(
            communityWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        communitySplitPane.setRightComponent(communityWorkArea);

        javax.swing.GroupLayout manageCommunitiesLayout = new javax.swing.GroupLayout(manageCommunities);
        manageCommunities.setLayout(manageCommunitiesLayout);
        manageCommunitiesLayout.setHorizontalGroup(
            manageCommunitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communitySplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        manageCommunitiesLayout.setVerticalGroup(
            manageCommunitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communitySplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Communities", manageCommunities);

        hospitalControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateHospital.setText("Create");
        btnCreateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalActionPerformed(evt);
            }
        });

        btnViewHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewHospital.setText("View");
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });

        btnUpdateHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateHospital.setText("Update");

        btnDeleteHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteHospital.setText("Delete");
        btnDeleteHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hospitalControlAreaLayout = new javax.swing.GroupLayout(hospitalControlArea);
        hospitalControlArea.setLayout(hospitalControlAreaLayout);
        hospitalControlAreaLayout.setHorizontalGroup(
            hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDeleteHospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        hospitalControlAreaLayout.setVerticalGroup(
            hospitalControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        hospitalSplitPane.setLeftComponent(hospitalControlArea);

        hospitalWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout hospitalWorkAreaLayout = new javax.swing.GroupLayout(hospitalWorkArea);
        hospitalWorkArea.setLayout(hospitalWorkAreaLayout);
        hospitalWorkAreaLayout.setHorizontalGroup(
            hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        hospitalWorkAreaLayout.setVerticalGroup(
            hospitalWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        hospitalSplitPane.setRightComponent(hospitalWorkArea);

        javax.swing.GroupLayout manageHospitalsLayout = new javax.swing.GroupLayout(manageHospitals);
        manageHospitals.setLayout(manageHospitalsLayout);
        manageHospitalsLayout.setHorizontalGroup(
            manageHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalSplitPane)
        );
        manageHospitalsLayout.setVerticalGroup(
            manageHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalSplitPane)
        );

        tabbedPane.addTab("Hospitals", manageHospitals);

        houseControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateHouse.setText("Create");
        btnCreateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHouseActionPerformed(evt);
            }
        });

        btnViewHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewHouse.setText("View");
        btnViewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHouseActionPerformed(evt);
            }
        });

        btnUpdateHospital1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateHospital1.setText("Update");

        btnDeleteHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteHouse.setText("Delete");
        btnDeleteHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout houseControlAreaLayout = new javax.swing.GroupLayout(houseControlArea);
        houseControlArea.setLayout(houseControlAreaLayout);
        houseControlAreaLayout.setHorizontalGroup(
            houseControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(houseControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateHospital1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDeleteHouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        houseControlAreaLayout.setVerticalGroup(
            houseControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        houseSplitPane.setLeftComponent(houseControlArea);

        houseWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout houseWorkAreaLayout = new javax.swing.GroupLayout(houseWorkArea);
        houseWorkArea.setLayout(houseWorkAreaLayout);
        houseWorkAreaLayout.setHorizontalGroup(
            houseWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        houseWorkAreaLayout.setVerticalGroup(
            houseWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        houseSplitPane.setRightComponent(houseWorkArea);

        javax.swing.GroupLayout manageHousesLayout = new javax.swing.GroupLayout(manageHouses);
        manageHouses.setLayout(manageHousesLayout);
        manageHousesLayout.setHorizontalGroup(
            manageHousesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(houseSplitPane)
        );
        manageHousesLayout.setVerticalGroup(
            manageHousesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(houseSplitPane)
        );

        tabbedPane.addTab("Houses", manageHouses);

        peopleControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreatePeople.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreatePeople.setText("Create");
        btnCreatePeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePeopleActionPerformed(evt);
            }
        });

        btnViewPeople.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewPeople.setText("View");
        btnViewPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPeopleActionPerformed(evt);
            }
        });

        btnUpdatePeople.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdatePeople.setText("Update");

        btnDeletePeople.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletePeople.setText("Delete");
        btnDeletePeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePeopleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout peopleControlAreaLayout = new javax.swing.GroupLayout(peopleControlArea);
        peopleControlArea.setLayout(peopleControlAreaLayout);
        peopleControlAreaLayout.setHorizontalGroup(
            peopleControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peopleControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peopleControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdatePeople, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDeletePeople, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreatePeople, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewPeople, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        peopleControlAreaLayout.setVerticalGroup(
            peopleControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peopleControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreatePeople, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdatePeople, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeletePeople, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        peopleSplitPane.setLeftComponent(peopleControlArea);

        peopleWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout peopleWorkAreaLayout = new javax.swing.GroupLayout(peopleWorkArea);
        peopleWorkArea.setLayout(peopleWorkAreaLayout);
        peopleWorkAreaLayout.setHorizontalGroup(
            peopleWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        peopleWorkAreaLayout.setVerticalGroup(
            peopleWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        peopleSplitPane.setRightComponent(peopleWorkArea);

        javax.swing.GroupLayout managePeopleLayout = new javax.swing.GroupLayout(managePeople);
        managePeople.setLayout(managePeopleLayout);
        managePeopleLayout.setHorizontalGroup(
            managePeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peopleSplitPane)
        );
        managePeopleLayout.setVerticalGroup(
            managePeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peopleSplitPane)
        );

        tabbedPane.addTab("People", managePeople);

        patientsDoctorsSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        patientsDoctorsControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnUpdatePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdatePatient.setText("Update");
        btnUpdatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientActionPerformed(evt);
            }
        });

        btnCreateDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateDoctor.setText("Create");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        btnUpdateDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateDoctor.setText("Update");
        btnUpdateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDoctorActionPerformed(evt);
            }
        });

        btnDeletePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletePatient.setText("Delete");
        btnDeletePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePatientActionPerformed(evt);
            }
        });

        btnDeleteDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteDoctor.setText("Delete");
        btnDeleteDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDoctorActionPerformed(evt);
            }
        });

        btnCreatePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreatePatient.setText("Create");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnViewDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewDoctor.setText("View");
        btnViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorActionPerformed(evt);
            }
        });

        btnViewPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewPatient.setText("View");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        lblPatientsDoctors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPatientsDoctors.setForeground(new java.awt.Color(255, 0, 0));
        lblPatientsDoctors.setText("                                                 Patients                                                                                                                           Doctors");

        javax.swing.GroupLayout patientsDoctorsControlAreaLayout = new javax.swing.GroupLayout(patientsDoctorsControlArea);
        patientsDoctorsControlArea.setLayout(patientsDoctorsControlAreaLayout);
        patientsDoctorsControlAreaLayout.setHorizontalGroup(
            patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientsDoctorsControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientsDoctorsControlAreaLayout.createSequentialGroup()
                        .addComponent(btnCreatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(btnViewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnUpdatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(btnDeletePatient, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(137, 137, 137)
                        .addComponent(btnCreateDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(btnViewDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(btnUpdateDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnDeleteDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(patientsDoctorsControlAreaLayout.createSequentialGroup()
                        .addComponent(lblPatientsDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        patientsDoctorsControlAreaLayout.setVerticalGroup(
            patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientsDoctorsControlAreaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPatientsDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientsDoctorsControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        patientsDoctorsSplitPane.setTopComponent(patientsDoctorsControlArea);

        patientsDoctorsWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout patientsDoctorsWorkAreaLayout = new javax.swing.GroupLayout(patientsDoctorsWorkArea);
        patientsDoctorsWorkArea.setLayout(patientsDoctorsWorkAreaLayout);
        patientsDoctorsWorkAreaLayout.setHorizontalGroup(
            patientsDoctorsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        patientsDoctorsWorkAreaLayout.setVerticalGroup(
            patientsDoctorsWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        patientsDoctorsSplitPane.setRightComponent(patientsDoctorsWorkArea);

        javax.swing.GroupLayout managePatientsDoctorsLayout = new javax.swing.GroupLayout(managePatientsDoctors);
        managePatientsDoctors.setLayout(managePatientsDoctorsLayout);
        managePatientsDoctorsLayout.setHorizontalGroup(
            managePatientsDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientsDoctorsSplitPane)
        );
        managePatientsDoctorsLayout.setVerticalGroup(
            managePatientsDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientsDoctorsSplitPane)
        );

        tabbedPane.addTab("Patients & Doctors", managePatientsDoctors);

        encounterControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnCreateEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateEncounter.setText("Create");
        btnCreateEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEncounterActionPerformed(evt);
            }
        });

        btnViewEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewEncounter.setText("View");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        btnUpdateEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateEncounter.setText("Update");

        btnDeleteEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteEncounter.setText("Delete");
        btnDeleteEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout encounterControlAreaLayout = new javax.swing.GroupLayout(encounterControlArea);
        encounterControlArea.setLayout(encounterControlAreaLayout);
        encounterControlAreaLayout.setHorizontalGroup(
            encounterControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encounterControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDeleteEncounter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnCreateEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnViewEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        encounterControlAreaLayout.setVerticalGroup(
            encounterControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterControlAreaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCreateEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        encounterSplitPane.setLeftComponent(encounterControlArea);

        encounterWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout encounterWorkAreaLayout = new javax.swing.GroupLayout(encounterWorkArea);
        encounterWorkArea.setLayout(encounterWorkAreaLayout);
        encounterWorkAreaLayout.setHorizontalGroup(
            encounterWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        encounterWorkAreaLayout.setVerticalGroup(
            encounterWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        encounterSplitPane.setRightComponent(encounterWorkArea);

        javax.swing.GroupLayout manageEncountersLayout = new javax.swing.GroupLayout(manageEncounters);
        manageEncounters.setLayout(manageEncountersLayout);
        manageEncountersLayout.setHorizontalGroup(
            manageEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encounterSplitPane)
        );
        manageEncountersLayout.setVerticalGroup(
            manageEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encounterSplitPane)
        );

        tabbedPane.addTab("Encounters", manageEncounters);

        lblSystemAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblSystemAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSystemAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lblSystemAdmin.setText("                                                                                        Welcome System Admin!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
            .addComponent(lblSystemAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHospitalActionPerformed

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
        viewHospitalJPanel viewHospital = new viewHospitalJPanel(hospitalDirectory);
        hospitalSplitPane.setRightComponent(viewHospital);
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnCreateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalActionPerformed
        // TODO add your handling code here:
        createHospitalJPanel createHospital = new createHospitalJPanel(cityDirectory, communityDirectory, hospitalDirectory);
        hospitalSplitPane.setRightComponent(createHospital);     
    }//GEN-LAST:event_btnCreateHospitalActionPerformed

    private void btnDeleteCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCommunityActionPerformed

    private void btnViewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunityActionPerformed
        // TODO add your handling code here:
        viewCommunityJPanel viewCommunity = new viewCommunityJPanel(communityDirectory);
        communitySplitPane.setRightComponent(viewCommunity);
    }//GEN-LAST:event_btnViewCommunityActionPerformed

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        // TODO add your handling code here:
        createCommunityJPanel createCommunity = new createCommunityJPanel(cityDirectory, communityDirectory);
        communitySplitPane.setRightComponent(createCommunity);
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void btnViewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCityActionPerformed
        // TODO add your handling code here:
        viewCityJPanel viewCity = new viewCityJPanel(cityDirectory);
        citySplitPane.setRightComponent(viewCity);
    }//GEN-LAST:event_btnViewCityActionPerformed

    private void btnCreateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCityActionPerformed
        // TODO add your handling code here:
        createCityJPanel createCity = new createCityJPanel(cityDirectory);
        citySplitPane.setRightComponent(createCity);
    }//GEN-LAST:event_btnCreateCityActionPerformed

    private void btnDeleteCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCityActionPerformed

    private void btnCreateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHouseActionPerformed
        // TODO add your handling code here:
        createHouseJPanel createHouse = new createHouseJPanel(cityDirectory, communityDirectory, houseDirectory);
        houseSplitPane.setRightComponent(createHouse);
    }//GEN-LAST:event_btnCreateHouseActionPerformed

    private void btnViewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHouseActionPerformed
        // TODO add your handling code here:
        viewHouseJPanel viewHouse = new viewHouseJPanel(houseDirectory);
        houseSplitPane.setRightComponent(viewHouse);
    }//GEN-LAST:event_btnViewHouseActionPerformed

    private void btnDeleteHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHouseActionPerformed

    private void btnCreatePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePeopleActionPerformed
        // TODO add your handling code here:
        createPersonJPanel createPerson = new createPersonJPanel(cityDirectory, communityDirectory, houseDirectory, personDirectory);
        peopleSplitPane.setRightComponent(createPerson);
    }//GEN-LAST:event_btnCreatePeopleActionPerformed

    private void btnViewPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPeopleActionPerformed
        // TODO add your handling code here:
        viewPersonJPanel viewPerson = new viewPersonJPanel(personDirectory);
        peopleSplitPane.setRightComponent(viewPerson);
    }//GEN-LAST:event_btnViewPeopleActionPerformed

    private void btnDeletePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePeopleActionPerformed

    private void btnCreateEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEncounterActionPerformed
        // TODO add your handling code here:
        createEncounters encounters = new createEncounters(patientDirectory, ecounterDirectory, hospitalDirectory);
        encounterSplitPane.setRightComponent(encounters);
    }//GEN-LAST:event_btnCreateEncounterActionPerformed

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        viewAllEncounters encounters = new viewAllEncounters(ecounterDirectory, patientDirectory);
        encounterSplitPane.setRightComponent(encounters);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    private void btnDeleteEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEncounterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteEncounterActionPerformed

    private void btnUpdatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePatientActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        createDoctorJPanel createDoctor = new createDoctorJPanel(cityDirectory, communityDirectory, personDirectory, doctorDirectory, hospitalDirectory);
        patientsDoctorsSplitPane.setBottomComponent(createDoctor);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnUpdateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateDoctorActionPerformed

    private void btnDeletePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePatientActionPerformed

    private void btnDeleteDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteDoctorActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        createPatientJPanel createPatient = new createPatientJPanel(cityDirectory, communityDirectory, personDirectory, patientDirectory);
        patientsDoctorsSplitPane.setBottomComponent(createPatient);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorActionPerformed
        // TODO add your handling code here:
        viewDoctorJPanel viewDoctor = new viewDoctorJPanel(doctorDirectory);
        patientsDoctorsSplitPane.setBottomComponent(viewDoctor);
    }//GEN-LAST:event_btnViewDoctorActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        viewPatientJPanel viewPatient = new viewPatientJPanel(patientDirectory);
        patientsDoctorsSplitPane.setBottomComponent(viewPatient);
    }//GEN-LAST:event_btnViewPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCity;
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreateEncounter;
    private javax.swing.JButton btnCreateHospital;
    private javax.swing.JButton btnCreateHouse;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnCreatePeople;
    private javax.swing.JButton btnDeleteCity;
    private javax.swing.JButton btnDeleteCommunity;
    private javax.swing.JButton btnDeleteDoctor;
    private javax.swing.JButton btnDeleteEncounter;
    private javax.swing.JButton btnDeleteHospital;
    private javax.swing.JButton btnDeleteHouse;
    private javax.swing.JButton btnDeletePatient;
    private javax.swing.JButton btnDeletePeople;
    private javax.swing.JButton btnUpdateCity;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JButton btnUpdateDoctor;
    private javax.swing.JButton btnUpdateEncounter;
    private javax.swing.JButton btnUpdateHospital;
    private javax.swing.JButton btnUpdateHospital1;
    private javax.swing.JButton btnUpdatePatient;
    private javax.swing.JButton btnUpdatePeople;
    private javax.swing.JButton btnViewCity;
    private javax.swing.JButton btnViewCommunity;
    private javax.swing.JButton btnViewDoctor;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JButton btnViewHouse;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JButton btnViewPeople;
    private javax.swing.JPanel cityControlArea;
    private javax.swing.JSplitPane citySplitPane;
    private javax.swing.JPanel cityWorkArea;
    private javax.swing.JPanel communityControlArea;
    private javax.swing.JSplitPane communitySplitPane;
    private javax.swing.JPanel communityWorkArea;
    private javax.swing.JPanel encounterControlArea;
    private javax.swing.JSplitPane encounterSplitPane;
    private javax.swing.JPanel encounterWorkArea;
    private javax.swing.JPanel hospitalControlArea;
    private javax.swing.JSplitPane hospitalSplitPane;
    private javax.swing.JPanel hospitalWorkArea;
    private javax.swing.JPanel houseControlArea;
    private javax.swing.JSplitPane houseSplitPane;
    private javax.swing.JPanel houseWorkArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPatientsDoctors;
    private javax.swing.JLabel lblSystemAdmin;
    private javax.swing.JPanel manageCities;
    private javax.swing.JPanel manageCommunities;
    private javax.swing.JPanel manageEncounters;
    private javax.swing.JPanel manageHospitals;
    private javax.swing.JPanel manageHouses;
    private javax.swing.JPanel managePatientsDoctors;
    private javax.swing.JPanel managePeople;
    private javax.swing.JPanel patientsDoctorsControlArea;
    private javax.swing.JSplitPane patientsDoctorsSplitPane;
    private javax.swing.JPanel patientsDoctorsWorkArea;
    private javax.swing.JPanel peopleControlArea;
    private javax.swing.JSplitPane peopleSplitPane;
    private javax.swing.JPanel peopleWorkArea;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
