/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.Encounter;
import model.EncounterDirectory;
import model.Patient;
import model.PatientDirectory;

/**
 *
 * @author shrey
 */
public class updateDoctorEncounters extends javax.swing.JPanel {

    /**
     * Creates new form viewDoctorEncounters
     */
    Doctor d;
    EncounterDirectory ed;
    PatientDirectory patientDirectory;
    
    public updateDoctorEncounters(Doctor d, EncounterDirectory ed, PatientDirectory patientDirectory) {
        initComponents();
        this.d = d;
        this.ed = ed;
        this.patientDirectory = patientDirectory;
        txtUID.setEditable(false);
        populateTable(d, ed);
    }
    
    private void populateTable(Doctor d, EncounterDirectory ed)
    {
        DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
        model.setRowCount(0);
        
        for(Encounter e:ed.getEncounterDirectory())
        {
            if(d.getName().equals(e.getDoctorName()))
            {
                Object[] row = new Object[5];
                row[0] = e.getEncounterID();
                row[1] = name(e);
                row[2] = e;
                row[3] = e.getHospitalName();
                row[4] = e.getEncounterSymptoms();
                model.addRow(row);
            }
        }
    }
    
    private String name(Encounter e)
    {
        for(Patient p:patientDirectory.getPatientDirectory())
        {
            if(p.getPatientId() == e.getPatientID())
            {
                return p.getName();
            }
        }
        return "";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateEncounters = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();
        txtEncounterSymptoms = new javax.swing.JTextField();
        lblEncounterID = new javax.swing.JLabel();
        lblEncounterDate = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtUID = new javax.swing.JTextField();
        txtEncounterDate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 255));

        updateEncounters.setBackground(new java.awt.Color(255, 255, 255));
        updateEncounters.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateEncounters.setForeground(new java.awt.Color(255, 0, 0));
        updateEncounters.setText("                                                                                        Update Encounters");

        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Encounter ID", "Patient Name", "Encounter Date", "Hospital Name", "Symptoms"
            }
        ));
        tblEncounters.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEncounters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncountersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEncounters);

        txtEncounterSymptoms.setPreferredSize(new java.awt.Dimension(72, 22));

        lblEncounterID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEncounterID.setText("Encounter ID :");

        lblEncounterDate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEncounterDate.setText("Encounter Date :");

        lblSymptoms.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSymptoms.setText("Symptoms :");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(104, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtUID.setPreferredSize(new java.awt.Dimension(72, 22));

        txtEncounterDate.setPreferredSize(new java.awt.Dimension(72, 22));
        txtEncounterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncounterDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateEncounters, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSymptoms, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEncounterID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEncounterDate, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEncounterSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateEncounters, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncounterID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncounterSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEncounters.getSelectedRow();
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row to update");
        }
        DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
        Encounter selectedEncounter = (Encounter) model.getValueAt(selectedRowIndex, 2);
        updateDetails(selectedEncounter);
        clearFormText();
        populateTable(d, ed);
      
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblEncountersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncountersMouseClicked
        // TODO add your handling code here:
        Encounter e = (Encounter)tblEncounters.getValueAt(tblEncounters.getSelectedRow(), 2);
        txtUID.setText(String.valueOf(e.getEncounterID()));
    }//GEN-LAST:event_tblEncountersMouseClicked

    private void txtEncounterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncounterDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncounterDateActionPerformed
    
    private void updateDetails(Encounter e)
    {
        e.setEncounterDate(txtEncounterDate.getText());
        e.setEncounterSymptoms(txtEncounterSymptoms.getText());
        JOptionPane.showMessageDialog(this, "Encounter Info Updated!");
    }
    
    private void clearFormText()
    {
        txtUID.setText("");
        txtEncounterDate.setText("");
        txtEncounterSymptoms.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEncounterDate;
    private javax.swing.JLabel lblEncounterID;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JTextField txtEncounterDate;
    private javax.swing.JTextField txtEncounterSymptoms;
    private javax.swing.JTextField txtUID;
    private javax.swing.JLabel updateEncounters;
    // End of variables declaration//GEN-END:variables
}
