/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.House;
import model.HouseDirectory;

/**
 *
 * @author shrey
 */
public class viewHouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewHouseJPanel
     */
    HouseDirectory houseDirectory;
    
    public viewHouseJPanel(HouseDirectory houseDirectory) {
        initComponents();
        this.houseDirectory = houseDirectory;
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tableViewHouses.getModel();
        model.setRowCount(0);
        
        for(House h:houseDirectory.getHouseDirectory())
        {
            Object[] row = new Object[3];
            row[0] = h;
            row[1] = h.getCommunityName();
            row[2] = h.getCityName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewHospitals = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewHouses = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 255));

        lblViewHospitals.setBackground(new java.awt.Color(255, 255, 255));
        lblViewHospitals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewHospitals.setForeground(new java.awt.Color(255, 0, 0));
        lblViewHospitals.setText("                                                                                    View Houses");

        tableViewHouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "House Address", "Community Name", "City Name"
            }
        ));
        jScrollPane1.setViewportView(tableViewHouses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblViewHospitals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewHospitals;
    private javax.swing.JTable tableViewHouses;
    // End of variables declaration//GEN-END:variables
}
