/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.DoctorDirectory;
import model.Hospital;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shrey
 */
public class viewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPersonJPanel
     */
    
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;
    
    public viewPersonJPanel(PersonDirectory personDirectory, PatientDirectory patientDirectory, DoctorDirectory doctorDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.doctorDirectory = doctorDirectory;
        populatePersonTable();
        /*populatePatientTable();
        populateDoctorTable();*/
    }
    
    private void populatePersonTable()
    {
        DefaultTableModel model = (DefaultTableModel) tableViewPerson.getModel();
        model.setRowCount(0);
        
        for(Person p:personDirectory.getPersonDirectory())
        {
            Object[] row = new Object[8];
            row[0] = p;
            row[1] = p.getGender();
            row[2] = p.getEmailId();
            row[3] = p.getAge();
            row[4] = p.getPhoneNumber();
            row[5] = p.getHouseAddress();
            row[6] = p.getCommunityName();
            row[7] = p.getCityName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonDirectory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewDoctor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableViewPatient = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableViewPerson = new javax.swing.JTable();
        lblViewPatients = new javax.swing.JLabel();
        lblViewDoctors = new javax.swing.JLabel();
        makeDoctor = new javax.swing.JButton();
        makePatient = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 255));

        lblPersonDirectory.setBackground(new java.awt.Color(255, 255, 255));
        lblPersonDirectory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPersonDirectory.setForeground(new java.awt.Color(255, 0, 0));
        lblPersonDirectory.setText("                                                                Select Person to make Patient / Doctor");

        tableViewDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableViewDoctor);

        tableViewPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableViewPatient);

        tableViewPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Email", "Age", "Phone", "Address", "Community", "City"
            }
        ));
        tableViewPerson.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tableViewPerson);

        lblViewPatients.setBackground(new java.awt.Color(255, 255, 255));
        lblViewPatients.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewPatients.setForeground(new java.awt.Color(255, 0, 0));
        lblViewPatients.setText("                                                                                 Patient Directory");

        lblViewDoctors.setBackground(new java.awt.Color(255, 255, 255));
        lblViewDoctors.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewDoctors.setForeground(new java.awt.Color(255, 0, 0));
        lblViewDoctors.setText("                                                                                   Doctor Directory");

        makeDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makeDoctor.setText("Make Doctor");
        makeDoctor.setPreferredSize(new java.awt.Dimension(103, 30));
        makeDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeDoctorActionPerformed(evt);
            }
        });

        makePatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makePatient.setText("Make Patient");
        makePatient.setPreferredSize(new java.awt.Dimension(104, 30));
        makePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPersonDirectory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                    .addComponent(lblViewPatients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(makePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(makeDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPersonDirectory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblViewPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblViewDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeDoctorActionPerformed

    private void makePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePatientActionPerformed
        // TODO add your handling code here:
        
        Person p = (Person)tableViewPerson.getValueAt(tableViewPerson.getSelectedRow(), 0);
        
    }//GEN-LAST:event_makePatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPersonDirectory;
    private javax.swing.JLabel lblViewDoctors;
    private javax.swing.JLabel lblViewPatients;
    private javax.swing.JButton makeDoctor;
    private javax.swing.JButton makePatient;
    private javax.swing.JTable tableViewDoctor;
    private javax.swing.JTable tableViewPatient;
    private javax.swing.JTable tableViewPerson;
    // End of variables declaration//GEN-END:variables
}
