/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.Hospital;
import model.HospitalDirectory;

/**
 *
 * @author shrey
 */
public class viewHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewHospitalJPanel
     */
    HospitalDirectory hospitalDirectory;
    
    public viewHospitalJPanel(HospitalDirectory hospitalDirectory) {
        initComponents();
        this.hospitalDirectory = hospitalDirectory;
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tableViewHospitals.getModel();
        model.setRowCount(0);
        
        for(Hospital h:hospitalDirectory.getHospitalDirectory())
        {
            Object[] row = new Object[4];
            row[0] = h;
            row[1] = h.getHospitalZip();
            row[2] = h.getHospitalCommunity();
            row[3] = h.getHospitalCity();
            model.addRow(row);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewHospitals = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewHospitals = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 255));

        lblViewHospitals.setBackground(new java.awt.Color(255, 255, 255));
        lblViewHospitals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewHospitals.setForeground(new java.awt.Color(255, 0, 0));
        lblViewHospitals.setText("                                                                                 View Hospitals");

        tableViewHospitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Zipcode", "Community Name", "City Name"
            }
        ));
        jScrollPane1.setViewportView(tableViewHospitals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewHospitals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblViewHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewHospitals;
    private javax.swing.JTable tableViewHospitals;
    // End of variables declaration//GEN-END:variables
}
