/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.Encounter;
import model.EncounterDirectory;
import model.Patient;
import model.PatientDirectory;

/**
 *
 * @author shrey
 */
public class viewDoctorEncounters extends javax.swing.JPanel {

    /**
     * Creates new form viewDoctorEncounters
     */
    Doctor d;
    EncounterDirectory ed;
    PatientDirectory patientDirectory;
    
    public viewDoctorEncounters(Doctor d, EncounterDirectory ed, PatientDirectory patientDirectory) {
        initComponents();
        this.d = d;
        this.ed = ed;
        this.patientDirectory = patientDirectory;
        populateTable(d, ed);
    }
    
    private void populateTable(Doctor d, EncounterDirectory ed)
    {
        DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
        model.setRowCount(0);
        
        for(Encounter e:ed.getEncounterDirectory())
        {
            if(d.getName().equals(e.getDoctorName()))
            {
                Object[] row = new Object[5];
                row[0] = e.getEncounterID();
                row[1] = name(e);
                row[2] = e;
                row[3] = e.getHospitalName();
                row[4] = e.getEncounterSymptoms();
                model.addRow(row);
            }
        }
    }
    
    private String name(Encounter e)
    {
        for(Patient p:patientDirectory.getPatientDirectory())
        {
            if(p.getPatientId() == e.getPatientID())
            {
                return p.getName();
            }
        }
        return "";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewEncounters = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 255));

        viewEncounters.setBackground(new java.awt.Color(255, 255, 255));
        viewEncounters.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewEncounters.setForeground(new java.awt.Color(255, 0, 0));
        viewEncounters.setText("                                                                                        View Encounters");

        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Encounter ID", "Patient Name", "Encounter Date", "Hospital Name", "Symptoms"
            }
        ));
        tblEncounters.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblEncounters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewEncounters, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewEncounters, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JLabel viewEncounters;
    // End of variables declaration//GEN-END:variables
}
