/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.Community;
import model.CommunityDirectory;

/**
 *
 * @author shrey
 */
public class viewCommunityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewCommunityJPanel
     */
    CommunityDirectory communityDirectory;
    
    public viewCommunityJPanel(CommunityDirectory communityDirectory) {
        initComponents();
        this.communityDirectory = communityDirectory;
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) viewCommunityTable.getModel();
        model.setRowCount(0);
        
        for(Community cm:communityDirectory.getCommunityDirectory())
        {
            Object[] row = new Object[2];
            row[0] = cm;
            row[1] = cm.getCommunityName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewCommunities = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewCommunityTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 255));

        lblViewCommunities.setBackground(new java.awt.Color(255, 255, 255));
        lblViewCommunities.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewCommunities.setForeground(new java.awt.Color(255, 0, 0));
        lblViewCommunities.setText("                                                                             View Communities");

        viewCommunityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "City Name", "Community Name"
            }
        ));
        jScrollPane1.setViewportView(viewCommunityTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewCommunities, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblViewCommunities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewCommunities;
    private javax.swing.JTable viewCommunityTable;
    // End of variables declaration//GEN-END:variables
}
